#!/bin/bash

cd /opt/spam_filter

days="30"
mail_dir="/srv/mail"
data_dir="/var/lib/spam_filter"
accounts=`cat accounts`
features="$data_dir/training_features"

# Clean-up features and vectors
#rm -f $features /srv/mail/filter/vectors /srv/mail/filter/messages

for account in $accounts; do
	if [ ! -d "$mail_dir/$account" ]; then
		echo "Account does not exist: $1"
		continue
	fi

	echo "Extrating features from emails for $account:"

	#find "$mail_dir/$account/cur" -type f -ctime -1 ! -name .\* -print | \
	#	xargs basename -a | cut -d , -f 1 >> $data_dir/messages

	echo "  Ham"
	find "$mail_dir/$account" -path */cur/* -type f -ctime -30 \
		! -name .\* -name *,S=[0-9]*:*S -print | \
		grep -iv -e spam -e junk | ./extract_features.py ham $features

	echo "  Spam"
	find "$mail_dir/$account" -path */cur/* -type f -ctime -30 ! -name .\* \
		-print | grep -i -e spam -e junk  | ./extract_features.py spam $features

	echo ""
done

# Add an extra document to the features to make room in Mallet's dictionary
#seq 1 1000000 | tr '\n' " " | sed '-e s/[ $]/:0 /g' -e 's/^/1 /' >> $features

